version: '3.3'

services:

  nginx-proxy:
    #image: jwilder/nginx-proxy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - huis-flix-network
    extra_hosts:
      - huis-flix.nl:${HOST_IP}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

#  postgres:
#    container_name: huis-flix-db
#    image: postgres:latest
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - huis-flix-network
#    volumes:
#      - postgres:/data/postgres

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - huis-flix-network
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 9080:8080
      - 7080:8080
    depends_on:
      - mysql
    networks:
      - huis-flix-network

  pgadmin:
    container_name: admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - huis-flix-network
    links:
      - mysql
    volumes:
      - pgadmin:/root/.pgadmin

networks:
  huis-flix-network:

volumes:
  mysql_data:
  pgadmin:
